// User Management
export const PERMISSION_CREATE_USER = 'CREATE_USER';
export const PERMISSION_UPDATE_USER = 'UPDATE_USER';
export const PERMISSION_DELETE_USER = 'DELETE_USER';
export const PERMISSION_VIEW_USER = 'VIEW_USER';
export const PERMISSION_MANAGE_USER_STATUS = 'MANAGE_USER_STATUS';

// Product Management
export const PERMISSION_CREATE_PRODUCT = 'CREATE_PRODUCT';
export const PERMISSION_UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const PERMISSION_DELETE_PRODUCT = 'DELETE_PRODUCT';
export const PERMISSION_VIEW_PRODUCT = 'VIEW_PRODUCT';
export const PERMISSION_APPROVE_PRODUCT = 'APPROVE_PRODUCT';

// Order Management
export const PERMISSION_CREATE_ORDER = 'CREATE_ORDER';
export const PERMISSION_UPDATE_ORDER = 'UPDATE_ORDER';
export const PERMISSION_VIEW_ORDER = 'VIEW_ORDER';
export const PERMISSION_CANCEL_ORDER = 'CANCEL_ORDER';
export const PERMISSION_MANAGE_ORDERS = 'MANAGE_ORDERS';

// Shop Management
export const PERMISSION_CREATE_SHOP = 'CREATE_SHOP';
export const PERMISSION_UPDATE_SHOP = 'UPDATE_SHOP';
export const PERMISSION_DELETE_SHOP = 'DELETE_SHOP';
export const PERMISSION_VIEW_SHOP = 'VIEW_SHOP';
export const PERMISSION_MANAGE_SHOP_STATUS = 'MANAGE_SHOP_STATUS';

// Category & Brand
export const PERMISSION_CREATE_CATEGORY = 'CREATE_CATEGORY';
export const PERMISSION_UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const PERMISSION_DELETE_CATEGORY = 'DELETE_CATEGORY';
export const PERMISSION_CREATE_BRAND = 'CREATE_BRAND';
export const PERMISSION_UPDATE_BRAND = 'UPDATE_BRAND';
export const PERMISSION_DELETE_BRAND = 'DELETE_BRAND';

// Review & Rating
export const PERMISSION_CREATE_REVIEW = 'CREATE_REVIEW';
export const PERMISSION_UPDATE_REVIEW = 'UPDATE_REVIEW';
export const PERMISSION_DELETE_REVIEW = 'DELETE_REVIEW';
export const PERMISSION_MODERATE_REVIEW = 'MODERATE_REVIEW';

// Voucher & Promotion
export const PERMISSION_CREATE_VOUCHER = 'CREATE_VOUCHER';
export const PERMISSION_UPDATE_VOUCHER = 'UPDATE_VOUCHER';
export const PERMISSION_DELETE_VOUCHER = 'DELETE_VOUCHER';
export const PERMISSION_MANAGE_PLATFORM_VOUCHER = 'MANAGE_PLATFORM_VOUCHER';

// Admin & System
export const PERMISSION_MANAGE_ROLES = 'MANAGE_ROLES';
export const PERMISSION_MANAGE_PERMISSIONS = 'MANAGE_PERMISSIONS';
export const PERMISSION_VIEW_AUDIT_LOG = 'VIEW_AUDIT_LOG';
export const PERMISSION_MANAGE_SYSTEM_SETTINGS = 'MANAGE_SYSTEM_SETTINGS';

// Address Management
export const PERMISSION_CREATE_ADDRESS = 'CREATE_ADDRESS';
export const PERMISSION_UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const PERMISSION_DELETE_ADDRESS = 'DELETE_ADDRESS';

// Reports
export const PERMISSION_VIEW_SHOP_REPORTS = 'VIEW_SHOP_REPORTS';
export const PERMISSION_VIEW_SYSTEM_REPORTS = 'VIEW_SYSTEM_REPORTS';

// Disputes
export const PERMISSION_MANAGE_DISPUTES = 'MANAGE_DISPUTES';



